name: lambda
version: 0.1.0.0
github: "zuqq/lambda"
author: "zuqq"

extra-source-files:
- README.md

dependencies:
- attoparsec
- base >= 4.7 && < 5
- containers
- microlens
- microlens-mtl
- pretty
- text
- transformers

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

tests:
  graze-doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
    - doctest
    - lambda
  graze-prop:
    main: Main.hs
    source-dirs: prop
    dependencies:
    - QuickCheck
    - lambda
