name:    lambda
version: 0.1.0.0
github:  "zuqq/lambda"
author:  "zuqq <noahheld17@gmail.com>"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- containers
- pretty
- transformers

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
